if not defined BUILD_SQLSERVER_ADMINISTRATIVE_VIEWS (set BUILD_SQLSERVER_ADMINISTRATIVE_VIEWS=M:\Temp\Universe.SqlServer.AdministrativeViews.CLI-BUILD)
rem mkdir %BUILD_SQLSERVER_ADMINISTRATIVE_VIEWS%\PUBLIC
if not defined COMPRESSION_LEVEL (set COMPRESSION_LEVEL=7)
